### ISSUE TITLE
Investigate in SELinux test Softfail when using Package_Set server

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#34] opened 2021-08-22 00:23 UTC
## Describe Issue

When using the PACKAGE_SET `server` the test module `/var/lib/openqa/share/tests/rocky/tests/_console_avc_crash.pm` softfails because the avcs logfile is not empty. (tested without package set as well as with `minimal`, which don't softfail)
This leads to packages which are issuing these avc denies: (or similar)

```bash
----
time->Fri Aug 20 15:39:02 2021
type=PROCTITLE msg=audit(1629488342.445:79): proctitle=2F62696E2F6C6F67696E002D70002D2D0020202020
type=SYSCALL msg=audit(1629488342.445:79): arch=c000003e syscall=137 success=no exit=-13 a0=7fdc3ff84d09 a1=7ffe23c39b40 a2=55dd6bd07640 a3=0 items=0 ppid=1 pid=1075 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty1 ses=4294967295 comm="login" exe="/usr/bin/login" subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1629488342.445:79): avc:  denied  { getattr } for  pid=1075 comm="login" name="/" dev="tmpfs" ino=12268 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
----
time->Fri Aug 20 15:39:13 2021
type=PROCTITLE msg=audit(1629488353.206:97): proctitle=2F62696E2F6C6F67696E002D70002D2D0020202020
type=SYSCALL msg=audit(1629488353.206:97): arch=c000003e syscall=137 success=no exit=-13 a0=7f65f7db1d09 a1=7ffc709f00c0 a2=559fbfe3e640 a3=0 items=0 ppid=1 pid=1148 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty4 ses=4294967295 comm="login" exe="/usr/bin/login" subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1629488353.206:97): avc:  denied  { getattr } for  pid=1148 comm="login" name="/" dev="tmpfs" ino=12268 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
----
time->Fri Aug 20 15:39:31 2021
type=PROCTITLE msg=audit(1629488371.169:114): proctitle=2F62696E2F6C6F67696E002D70002D2D0020202020
type=SYSCALL msg=audit(1629488371.169:114): arch=c000003e syscall=137 success=no exit=-13 a0=7f7d4b0c3d09 a1=7ffe84812bc0 a2=55eb5eaf2640 a3=0 items=0 ppid=1 pid=1193 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty3 ses=4294967295 comm="login" exe="/usr/bin/login" subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1629488371.169:114): avc:  denied  { getattr } for  pid=1193 comm="login" name="/" dev="tmpfs" ino=12268 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
```

## Planned Action

- Investigate in which packages trigger these avc messages
- Fix the issue in the packages or if this is common behavior adjust the test to not fail on these entries

**Comment by akatch** [comment] 2021-11-17 04:14
These seem to have gone away in the most recent round of tests. If someone else can confirm, could we close this?

**Comment by lumarel** [comment] 2021-12-16 22:50
For me they still show up 🤔

**Comment by tcooper** [comment] 2022-02-07 00:07
I've spent some time looking at these and trying to discover if this is fixed or typically ignored by Fedora QA.

It seems the common AVC we see...

```
----
time->Sun Feb  6 07:43:15 2022
type=PROCTITLE msg=audit(1644151395.837:72): proctitle=2F62696E2F6C6F67696E002D70002D2D0020202020
type=SYSCALL msg=audit(1644151395.837:72): arch=c000003e syscall=137 success=no exit=-13 a0=7fe8da318ca9 a1=7ffff258b270 a2=5604cd0ed440 a3=0 items=0 ppid=1 pid=1079 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty1 ses=4294967295 comm="login" exe="/usr/bin/login" subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1644151395.837:72): avc:  denied  { getattr } for  pid=1079 comm="login" name="/" dev="tmpfs" ino=12422 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
----
time->Sun Feb  6 07:43:28 2022
type=PROCTITLE msg=audit(1644151408.969:95): proctitle=2F62696E2F6C6F67696E002D70002D2D0020202020
type=SYSCALL msg=audit(1644151408.969:95): arch=c000003e syscall=137 success=no exit=-13 a0=7f28f8510ca9 a1=7ffc56ea3fd0 a2=55acd04c2440 a3=0 items=0 ppid=1 pid=1168 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty1 ses=4294967295 comm="login" exe="/usr/bin/login" subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1644151408.969:95): avc:  denied  { getattr } for  pid=1168 comm="login" name="/" dev="tmpfs" ino=12422 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
----
time->Sun Feb  6 07:44:14 2022
type=PROCTITLE msg=audit(1644151454.093:115): proctitle=2F62696E2F6C6F67696E002D70002D2D0020202020
type=SYSCALL msg=audit(1644151454.093:115): arch=c000003e syscall=137 success=no exit=-13 a0=7f1409482ca9 a1=7ffc0f0de660 a2=55616a674440 a3=0 items=0 ppid=1 pid=1253 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty3 ses=4294967295 comm="login" exe="/usr/bin/login" subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1644151454.093:115): avc:  denied  { getattr } for  pid=1253 comm="login" name="/" dev="tmpfs" ino=12422 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
```

...appears to be caused in early boot when `systemd` still hasn't completed switchroot.

Fedora typically doesn't allow any workarounds for AVC's for release blocking deliverables but I haven't been able to find a Bugzilla entry specifically addressing the old version of Fedora that RHEL, and thus Rocky, 8.5 is based off of.

I'm willing to ignore these AVCs since they are never seen in later boot phases and are easy to resolve in a real system...

```
# ausearch -c 'login' --raw | audit2allow -M my-login; semodule -X 300 -i my-login.pp
```

We can/should recheck for `VERSION=8.6` and see if updated `selinux-policy*` packages resolve this issue.

Any other opinions/comments?

**Comment by akatch** [comment] 2022-02-10 00:36
Seems reasonable to me. I went back and ran these again just to make sure I wasn't misremembering, and I get zero softfails with PACKAGE_SET=server and FLAVOR=minimal-iso, but I do see the softfails for FLAVOR=boot-iso and dvd-iso.

I'd agree that we should hold off doing any more with this until we know whether 8.6 helps at all.

**Comment by akatch** [comment] 2022-06-10 04:05
I've confirmed that I no longer see softfails for PACKAGE_SET=server when FLAVOR=boot-iso or minimal-iso since 8.6. Closing.

**Closed by akatch** 2022-06-10 04:05 UTC
Labels: priority: low, type: bug
